name: Build APK Free (Auto Init)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install React Native CLI
        run: npm install -g react-native-cli

      - name: Init React Native Project (if not exists)
        run: |
          if [ ! -d "android" ]; then
            npx react-native@0.73.6 init TempProject --version 0.73.6 --skip-install
            mv TempProject/* .
            mv TempProject/.??* .
            rmdir TempProject
            npm install
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Oboe + KissFFT
        run: |
          mkdir -p native/cpp
          rm -rf native/cpp/oboe native/cpp/kissfft
          git clone --depth 1 https://github.com/google/oboe.git native/cpp/oboe
          git clone --depth 1 https://github.com/mborgerding/kissfft.git native/cpp/kissfft

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleRelease \
            -PabiFilters=arm64-v8a,armeabi-v7a

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: eq-master-free-apks
          path: android/app/build/outputs/apk/release/*.apk
